# Generated by Django 4.2.15 on 2024-10-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason'), ('Interior Designer', 'Interior Designer'), ('Roofer', 'Rooer'), ('Tiler', 'Tiler'), ('Landscaper', 'Landscaper')], max_length=50),
        ),
    ]
