# Generated by Django 4.2.15 on 2024-10-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
