# Generated by Django 4.2.15 on 2024-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_employee_timesheet_task_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
