# Generated by Django 4.2.15 on 2024-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_task_department_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason'), ('Interior Designer', 'Interior Designer'), ('Roofer', 'Roofer'), ('Tiler', 'Tiler'), ('Landscaper', 'Landscaper')], max_length=50),
        ),
    ]
