# Generated by Django 5.1.6 on 2025-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_employee_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Mason', 'Mason'), ('Interior Designer', 'Interior Designer'), ('Roofer', 'Roofer'), ('Tiler', 'Tiler'), ('Landscaper', 'Landscaper'), ('Material Supply', 'Material Supply'), ('Labor Services', 'Labor Services'), ('Equipment Rental', 'Equipment Rental'), ('Project Planning', 'Project Planning'), ('Finishing Work', 'Finishing Work'), ('Renovation', 'Renovation')], max_length=50),
        ),
    ]
