# Generated by Django 5.1.4 on 2025-03-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_servicerequest_address_servicerequest_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
